#!/usr/bin/python
#-*-cod:utf-8-*-
from selenium import webdriver
from  time import sleep
dr=webdriver.Chrome()
sleep(1)
dr.get('https://mail.qq.com/cgi-bin/loginpage')
sleep(1)
dr.switch_to.frame('login_frame')
sleep(1)
dr.find_element_by_xpath('//*[@id="switcher_plogin"]').click()
sleep(2)

dr.find_element_by_id('u').send_keys('2393854643@qq.com')
sleep(1)
dr.find_element_by_id('p').send_keys('zyw2010923?')
sleep(1)
dr.find_element_by_xpath('//*[@id="login_button"]').click()
sleep(3)
dr.find_element_by_id('composebtn').click()
sleep(1)
dr.switch_to.frame('mainFrame')
sleep(1)
dr.find_element_by_xpath('//*[@id="toAreaCtrl"]/div[2]/input').send_keys('179084191@qq.com')
sleep(1)
dr.find_element_by_id('subject').send_keys('web自动化发送邮件')
sleep(1)
dr.switch_to.default_content()
sleep(1)
dr.switch_to.frame('mainFrame')
sleep(1)
dr.find_element_by_xpath('//*[@id="sendtimepadding"]/div[7]/table/tbody/tr/td[1]/div').click()
sleep(2)
a = dr.find_element_by_class_name('qmEditorIfrmEditArea')
dr.switch_to.frame(a)
sleep(2)
dr.find_element_by_xpath('/html/body').send_keys('这是一封由web网页自动化python脚本代码写出来的发送的邮件')
sleep(1)
dr.switch_to.default_content()
sleep(1)
dr.switch_to.frame('mainFrame')
sleep(1)
dr.find_element_by_css_selector('#toolbar > div > a:nth-child(2)').click()
sleep(2)
print('邮件发送成功')
sleep(5)
dr.quit()

